language: cpp

os: linux
sudo: true
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - cmake-data
      - cmake
      - lcov

before_install:
    - sudo add-apt-repository -y ppa:mhier/libboost-latest
    - sudo apt-get update

install:
    - sudo apt-get install libboost1.67-dev
    
script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - mkdir -p build
     - cd build
     - export CC=gcc-5
     - export CXX=g++-5
     - cmake -DCMAKE_BUILD_TYPE=Debug .. 
     - make
     - make test

after_success:
     # Creating report
     - cd ${TRAVIS_BUILD_DIR}
     - lcov --directory . --capture --output-file coverage.info # capture coverage info
     - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
     - lcov --list coverage.info #debug info
     # Uploading report to CodeCov
     - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
