language: cpp

os: linux
sudo: true
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - cmake-data
      - cmake

before_install:
    - sudo add-apt-repository ppa:mhier/libboost-latest
    - sudo apt-get update

install:
    - sudo apt-get install libboost1.67-dev

env:
    - CC=gcc-5
    - CXX=g++-5

script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - mkdir -p build
     - cd build
     - cmake -DCMAKE_BUILD_TYPE=Debug .. 
     - make
     - make test
     - make coverage
