language: cpp

os: linux
sudo: true
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - cmake-data
      - cmake
      - lcov

before_install:
    - sudo add-apt-repository -y ppa:mhier/libboost-latest
    - sudo apt-get update

install:
    - sudo apt-get install libboost1.67-dev
    
script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - mkdir -p build
     - cd build
     - export CC=gcc-5
     - export CXX=g++-5
     - cmake -DCMAKE_BUILD_TYPE=Debug .. 
     - make
     - make test
     - make coverage
