language: cpp

os:
 - linux
 - osx
sudo: true
dist: trusty

env:
  - CC=gcc-5 CXX=g++-5 GCOV=gcov-5 PKG=g++-5
  - CC=gcc-6 CXX=g++-6 GCOV=gcov-6 PKG=g++-6
  - CC=gcc-7 CXX=g++-7 GCOV=gcov-7 PKG=g++-7
  - CC=clang CXX=clang++ GCOV=llvm-cov PKG="clang llvm"

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo add-apt-repository -y ppa:mhier/libboost-latest
    - sudo apt-get update

install:
    - sudo apt-get install libboost1.67-dev cmake lcov
    - sudo apt-get install ${PKG}
    
script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - mkdir -p build
     - cd build
     - cmake -DCMAKE_BUILD_TYPE=Debug .. 
     - make
     - make test

after_success:
     # Creating report
     - cd ${TRAVIS_BUILD_DIR}
     - lcov --gcov-tool ${GCOV} --directory . --capture --output-file coverage.info # capture coverage info
     - lcov --gcov-tool ${GCOV} --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
     - lcov --gcov-tool ${GCOV} --list coverage.info #debug info
     # Uploading report to CodeCov
     - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
